<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/vendor/bootstrap/css/bootstrap.min.css">
    <title>Inserir</title>
</head>

<body>
    <div class="container">
        <h1 class="text-center">Inserir Carro</h1>
        <div class="d-flex justify-content-center">
            <!-- Aqui eu fiz um botão para voltar para a tela principal -->
            <a href="/" class='btn btn-primary'>Voltar</a>
        </div>

        <!-- Aqui eu fiz um formulario para enviar para inserir um carro -->
        <form action="/inserir/" method="post">

            <div class="col-12 d-flex justify-content-center my-2">
                <label class="mr-2">Modelo</label>
                <input type="text" name="modelo">
            </div>
            <div class="col-12 d-flex justify-content-center my-2">

                <label class="mr-2">Marca</label>
                <input type="text" name="marca">
            </div>
            <div class="col-12 d-flex justify-content-center my-2">
                <label class="mr-2">Ano</label>
                <input type="number" name="ano">
            </div>
            <div class="col-12 d-flex justify-content-center my-2">
                <label class="mr-2">Dono</label>
                <input type="text" name="nome">
            </div>

            <div class="col-12 d-flex justify-content-center my-2">
                <button type="submit">Inserir</button>
            </div>
        </form>
    </div>

</body>

</html>